#!/bin/bash
echo "starting:"

#to access gpio you must be root, thats why it runs using sudo
 nohup sudo java -jar /home/pi/automation/target/doorbell-1.0-SNAPSHOT.jar server /home/pi/automation/development.yml  &
